resources:
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:jeffellin/spring-petclinic-microservices.git
    branch: version
    file: vets-version
    private_key: ((pipeline-secret.git-private_key))
- name: source-code
  type: git
  source:
    uri: git@github.com:jeffellin/spring-petclinic-microservices.git
    branch: k8s
    paths: 
     - spring-petclinic-vets-service/*
    private_key: ((pipeline-secret.git-private_key))
jobs:
  - name: build-project
    serial: true
    plan:
      - get: source-code
        trigger: true
      - get: version
        params: {bump: minor}
      - task: build-project
        file: source-code/spring-petclinic-vets-service/ci/tasks/maven-build-task.yml
      - put: version
        params: {file: version/version}