kind: Service
apiVersion: v1
metadata:
  name: discovery-server
spec:
  selector:
    app: petclinic
    component: discoveryserver
  type:  ClusterIP
  ports:
  - name:  http
    port:  8761
    targetPort:  8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      component: discoveryserver
  template:
    metadata:
      labels:
        app: petclinic
        component: discoveryserver
    spec:
      containers:
      - name: discoery-server
        image: ellinj/petclinic-discovery-server
        ports:
            - containerPort: 8761
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker