kind: Service
apiVersion: v1
metadata:
  name: grafana-server
spec:
  selector:
    app: petclinic
    component: grafana-server
  type:  ClusterIP
  ports:
  - name:  http
    port:  9411
    targetPort:  9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      component: grafana-server
  template:
    metadata:
      labels:
        app: petclinic
        component: grafana-server
    spec:
      containers:
      - name: grafana-server
        image: registry.ellin.net/petclinic/grafana
        ports:
            - containerPort: 9411
       