kind: Service
apiVersion: v1
metadata:
  name: tracing-server
spec:
  selector:
    app: petclinic
    component: tracing-server
  type:  ClusterIP
  ports:
  - name:  http
    port:  9411
    targetPort:  9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      component: tracing-server
  template:
    metadata:
      labels:
        app: petclinic
        component: tracing-server
    spec:
      containers:
      - name: tracing-server
        image: openzipkin/zipkin
        ports:
            - containerPort: 9411
        env:
          - name: JAVA_OPTS
            value: -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom