resources:
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:jeffellin/spring-petclinic-microservices.git
    branch: version
    file: grafana-version
    private_key: ((pipeline-secret.git-private_key))
- name: source-code
  type: git
  source:
    uri: git@github.com:jeffellin/spring-petclinic-microservices.git
    branch: k8s
    paths: 
      - docker/grafana/*
    private_key: ((pipeline-secret.git-private_key))
- name: docker-image
  type: docker-image
  source:
    repository: ellinj/spring-petclinic-grafana
    username: ((pipeline-secret.docker-email))
    password: ((pipeline-secret.docker-password))
jobs:
  - name: build-project
    serial: true
    plan:
      - get: source-code
        trigger: true
      - get: version
        params: {bump: minor}
      - put: version
        params: {file: version/version}
      - put: docker-image
        params:
          build: source-code/docker/grafana
          tag_file: version/version
          tag_as_latest: true
      