resources:
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:jeffellin/spring-petclinic-microservices.git
    branch: version
    file: ((module))-version
    private_key: ((pipeline-secret.git-private_key))
- name: source-code
  type: git
  source:
    uri: git@github.com:jeffellin/spring-petclinic-microservices.git
    branch: k8s
    paths: 
      - ((module))/*
      - ci/*
    private_key: ((pipeline-secret.git-private_key))
- name: source-code-gitops
  type: git
  source:
    uri: git@github.com:jeffellin/spring-petclinic-gitops.git
    branch: master
    private_key: ((pipeline-secret.git-private_key))
- name: docker-image
  type: docker-image
  source:
    repository: ellinj/((module))
    username: ((pipeline-secret.docker-email))
    password: ((pipeline-secret.docker-password))
jobs:
  - name: build-project
    serial: true
    plan:
      - get: source-code
        trigger: true
      - get: source-code-gitops
        trigger: false
      - get: version
        params: {bump: minor}
      - task: build-project
        file: source-code/ci/tasks/maven-build-task.yml
        params:
           APP_NAME: ((module))
      - task: update-versions
        file: source-code/ci/tasks/update-build-task.yml
        params:
           APP_NAME: ((module))
      - put: version
        params: {file: version/version}
      - put: docker-image
        params:
          build: packed-release/target
          tag_file: version/version
          tag_as_latest: true
          build_args: 
            ARTIFACT_NAME: ((module))
            DOCKERIZE_VERSION: v0.6.1
      - put: source-code-gitops 
        params: 
          repository: gitops
          force: true