---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl
    tag: latest

inputs:
  - name: release
  - name: docker-image
  - name: source-code
outputs:
  - name: pks-build
  - naem: gitops-out
run:
  path: /bin/bash
  args:
    - source-code/ci/tasks/push-pks.sh